# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ef3f0962-af42-4a0b-9bfb-4018cd32d1d3";
      fsType = "ext4";
    };

  fileSystems."/nix/store" =
    { device = "/nix/store";
      fsType = "none";
      options = [ "bind" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/C292-8F3B";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/f45456dd-f583-48c1-b099-529afcaf6e0a"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-1c485c4d7fa0.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-2e6ee140c0d7.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-67241c4ca35b.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-681e2f1222eb.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-84a71e82b451.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-88143129e8ab.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-9b5ec6aaabf4.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-app.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-d6ff9d5daa0d.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-elastic.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp15s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp16s0.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
